Added changes to logging document to support 4.7
OpenLiberty/open-liberty-operator pull request #232
Opened 2021-05-04 16:53 UTC by randyclee

Fixes: https://github.ibm.com/websphere/WS-CD-Open/issues/23559 and https://github.ibm.com/websphere/WS-CD-Open/issues/23558

2021-05-06 02:22 UTC, Channyboy commented on doc/openshift-monitoring.adoc
> -        port: 9080-tcp
The code snippet shows as :
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: myapp-monitor
    labels:
    k8s-app: myapp-monitor
    namespace: myapp
spec:
    selector:
    matchLabels:
        app: example-app
    endpoints:
    - interval: 30s
      path: /metrics
      port: 9080-tcp
```      
Encountered issue:
`error: error parsing promSM.yaml: error converting YAML to JSON: yaml: line 13: mapping values are not allowed in this context`

Formatting like instead worked for me:
the `interval` `path` and `port` were moved over and the `label` was moved over for proper formatting.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: myapp-monitor
    labels:
      k8s-app: myapp-monitor
    namespace: myapp
spec:
    selector:
    matchLabels:
        app: example-app
    endpoints:
      - interval: 30s
        path: /metrics
        port: 9080-tcp
```

2021-06-07 19:00 UTC, donbourne requested changes

2021-06-24 19:39 UTC, donbourne commented on doc/openshift-logging.adoc
> +To install the OpenShift Logging component, follow the OpenShift guide  link:++https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-deploying.html++[Deploying OpenShift Logging].
Deploying OpenShift Logging -> Installing OpenShift Logging

2021-06-26 12:38 UTC, donbourne approved these changes

2021-06-26 12:39 UTC, donbourne commented
@randyclee , please squash your commits on this :-)

2021-06-29 17:55 UTC, merged