Update observability logging doc to include new JSON log parsing capa…
OpenLiberty/open-liberty-operator pull request #241
Opened 2021-09-08 16:07 UTC by ellen-lau

This PR is for updating the Observability Logging doc to include the new JSON log parsing capability added in RHOCP 4.7+.

2021-09-15 21:23 UTC, donbourne requested changes

2021-09-15 21:23 UTC, donbourne commented on doc/openshift-logging-rhocp_4.7+.adoc
> +To import the dashboard and its associated objects, navigate back to the **Management** page and click **Saved Objects**. Click **Import** and select the dashboard file. When prompted, click the **Ye
We need to mention where to get these dashboard files, as the line above seems not to flow from the preceding text.

same comment also applies to the 4.2-4.6 doc.

2021-10-05 16:41 UTC, ellen-lau commented
@donbourne, based off Anthony's run through of the guide, I made a minor change to the label creation section; users should be instructed to add the label to the OpenLibertyApplication and then they should restart their deployment afterwards, since this will automatically add the label to their service and pod. I've also added the link to the dashboard directory for both docs.

2021-10-06 01:01 UTC, donbourne approved these changes

2021-10-27 17:53 UTC, merged